# Generated by Django 5.1 on 2024-10-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Admin', 'Admin')], default='Customer', max_length=10, null=True),
        ),
    ]
