# Generated by Django 5.1 on 2024-10-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='userImage',
            field=models.ImageField(blank=True, default='static/images/userImageDefault.png', null=True, upload_to='products/'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
