# Generated by Django 5.1 on 2024-10-10 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customer_gender_alter_customer_userimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='userImage',
            field=models.ImageField(blank=True, default='static/images/userImageDefault.png', null=True, upload_to='customers/'),
        ),
    ]
