# Generated by Django 5.1 on 2024-10-10 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customer_userimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dateOfBirth',
            field=models.DateField(blank=True, default='2000-01-01', max_length=10, null=True),
        ),
    ]
