# Generated by Django 5.1 on 2024-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.CharField(default='2024-10-11 20:55:18', max_length=19),
        ),
    ]
