# Generated by Django 5.1 on 2024-10-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('productDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.CharField(default='2024-10-11 15:55:38', max_length=19)),
                ('orderAmount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('itemQuantity', models.PositiveIntegerField(default=1)),
                ('orderStatus', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=10)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetail.item')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('customer', 'item', 'orderDate')},
            },
        ),
    ]
