# Generated by Django 5.1 on 2024-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productDetail', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='productID',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sizeID',
            new_name='size',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
        migrations.AlterModelTable(
            name='size',
            table='size',
        ),
    ]
