# Generated by Django 5.1 on 2024-10-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='orderAmount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
