# Generated by Django 5.1 on 2024-10-09 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_remove_order_amount_order_orderamount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippingAddress',
        ),
    ]
