# Generated by Django 5.1 on 2024-10-09 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_customer_gender'),
        ('productDetail', '0001_initial'),
        ('purchase', '0003_remove_order_shippingaddress'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('userID', 'itemID', 'orderDate')},
        ),
    ]
