# Generated by Django 5.1 on 2024-10-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
        ('purchase', '0011_alter_order_orderdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='orderID',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='paymentStatus',
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='history.order'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.CharField(default='2024-10-10 16:56:54', max_length=19),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paymentMethod',
            field=models.CharField(choices=[('Credit Card', 'Credit Card'), ('COD', 'COD')], default='Credit Card', max_length=12),
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
