# Generated by Django 5.1 on 2024-10-10 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_remove_payment_orderid_remove_payment_paymentstatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.CharField(default='2024-10-10 19:05:24', max_length=19),
        ),
    ]
