# Generated by Django 5.1 on 2024-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0015_alter_payment_paymentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.CharField(default='2024-10-10 21:08:46', max_length=19),
        ),
    ]
