# Generated by Django 5.1 on 2024-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='customerID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='productID',
            new_name='product',
        ),
    ]
