# Generated by Django 5.1 on 2024-10-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_rename_customerid_review_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.CharField(default='2024-10-10 21:07:03', max_length=19),
        ),
    ]
