# Generated by Django 5.1 on 2024-10-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_reviewdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='review',
            name='reviewDate',
            field=models.CharField(default='2024-10-10 21:08:46', max_length=19),
        ),
    ]
