# Generated by Django 5.1 on 2024-10-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_alter_customer_dateofbirth'),
        ('productDetail', '0002_rename_productid_item_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False)),
                ('orderDate', models.CharField(default='2024-10-10 16:56:54', max_length=19)),
                ('orderAmount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('itemQuantity', models.PositiveIntegerField(default=1)),
                ('orderStatus', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=10)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetail.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
            options={
                'db_table': 'order',
                'unique_together': {('user', 'item', 'orderDate')},
            },
        ),
    ]
