# Generated by Django 5.1 on 2024-10-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customer_dateofbirth'),
        ('history', '0002_alter_order_orderdate'),
        ('productDetail', '0002_rename_productid_item_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='customer',
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.CharField(default='2024-10-10 19:48:59', max_length=19),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('customer', 'item', 'orderDate')},
        ),
    ]
