# Generated by Django 5.1 on 2024-10-10 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customer_dateofbirth'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='imageURL',
        ),
        migrations.AddField(
            model_name='product',
            name='productImage',
            field=models.ImageField(default='static/images/userImageDefault.png', upload_to='products/'),
        ),
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
            options={
                'db_table': 'userInterest',
            },
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
