# Generated by Django 5.1 on 2024-10-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='paymentDate',
            field=models.CharField(default='2024-10-11 20:55:18', max_length=19),
        ),
    ]
