# Generated by Django 5.1 on 2024-10-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('productDetail', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartID', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmount', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cartID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('itemID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetail.item')),
            ],
            options={
                'unique_together': {('cartID', 'itemID')},
            },
        ),
    ]
