# Generated by Django 5.1 on 2024-10-10 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('productDetail', '0002_rename_productid_item_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='userID',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cartID',
            new_name='cart',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='itemID',
            new_name='item',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'item')},
        ),
        migrations.AlterModelTable(
            name='cart',
            table='cart',
        ),
        migrations.AlterModelTable(
            name='cartitem',
            table='cartItem',
        ),
    ]
