# Generated by Django 5.1 on 2024-10-11 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('sizeID', models.AutoField(primary_key=True, serialize=False)),
                ('sizeName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemID', models.AutoField(primary_key=True, serialize=False)),
                ('stockQuantity', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productDetail.size')),
            ],
            options={
                'db_table': 'item',
            },
        ),
    ]
